import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import {Loader} from "@/components/shared/loader";

const nunito = Nunito({
    subsets: ['cyrillic'],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: "Car Dealer App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.variable}
      >
          <Suspense
              fallback={
              <div className="flex items-center justify-center h-screen">
                <Loader/>
              </div>}
          >
              {children}
          </Suspense>
      </body>
    </html>
  );
}
